name: Android UI Tests

on: pull_request

jobs:
  android-test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create Secrets Properties File
        run: touch secrets.properties

      - name: Add secret auth token
        run: echo "AUTHTOKEN=\""${{ secrets.AUTH_TOKEN }}"\"" >> secrets.properties

      - name: Add base url
        run: echo "BASEURL=\""${{ secrets.BASE_URL }}"\"" >> secrets.properties

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Run Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew app:connectedCheck