name : Android Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK
        uses: action/setup-java@v1
        with:
          java-version: 1.11

      - name: Build project
        run: ./gradlew assemble

      - name: Run tests
        run: ./gradlew test
