name : Android Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Create Local Properties File
        run: touch local.properties

      - name: Add secret auth token
        run: echo "AUTHTOKEN=\""${{ secrets.AUTH_TOKEN }}"\"" >> secrets.properties

      - name: Add base url
        run: echo "BASEURL=\""${{ secrets.BASE_URL }}"\"" >> secrets.properties

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Build project
        run: ./gradlew assemble

      - name: Run tests
        run: ./gradlew test
